#!/bin/bash

# Connect to Existing AWS S3 and CloudFront Setup
# Use this script if you already have an S3 bucket and CloudFront distribution

set -e

echo "=========================================="
echo "Connect to Existing AWS Infrastructure"
echo "=========================================="
echo ""
echo "This script will help you connect to your existing S3 bucket and CloudFront distribution."
echo ""

# Prompt for bucket name
read -p "Enter your existing S3 bucket name: " BUCKET_NAME

if [ -z "$BUCKET_NAME" ]; then
    echo "❌ Error: Bucket name is required"
    exit 1
fi

# Verify bucket exists
echo ""
echo "🔍 Verifying bucket exists..."
if aws s3 ls "s3://$BUCKET_NAME" &> /dev/null; then
    echo "✅ Bucket found: $BUCKET_NAME"
else
    echo "❌ Error: Bucket '$BUCKET_NAME' not found or you don't have access"
    exit 1
fi

# Get bucket region
REGION=$(aws s3api get-bucket-location --bucket "$BUCKET_NAME" --query 'LocationConstraint' --output text 2>/dev/null || echo "us-east-1")
if [ "$REGION" = "None" ] || [ -z "$REGION" ]; then
    REGION="us-east-1"
fi

echo "📍 Region: $REGION"

# Check if bucket is configured for website hosting
WEBSITE_CONFIG=$(aws s3api get-bucket-website --bucket "$BUCKET_NAME" 2>/dev/null || echo "")

if [ -z "$WEBSITE_CONFIG" ]; then
    echo "⚠️  Warning: Bucket is not configured for static website hosting"
    read -p "Would you like to enable it? (y/n): " ENABLE_WEBSITE
    
    if [ "$ENABLE_WEBSITE" = "y" ]; then
        aws s3 website "s3://$BUCKET_NAME" \
            --index-document index.html \
            --error-document 404.html
        echo "✅ Static website hosting enabled"
    fi
fi

WEBSITE_URL="http://$BUCKET_NAME.s3-website-$REGION.amazonaws.com"

# Prompt for CloudFront distribution ID (optional)
echo ""
read -p "Do you have a CloudFront distribution? (y/n): " HAS_CLOUDFRONT

CLOUDFRONT_DISTRIBUTION_ID=""
CLOUDFRONT_URL=""

if [ "$HAS_CLOUDFRONT" = "y" ]; then
    read -p "Enter your CloudFront distribution ID: " CLOUDFRONT_DISTRIBUTION_ID
    
    if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
        # Verify distribution exists
        echo "🔍 Verifying CloudFront distribution..."
        CLOUDFRONT_DOMAIN=$(aws cloudfront get-distribution \
            --id "$CLOUDFRONT_DISTRIBUTION_ID" \
            --query 'Distribution.DomainName' \
            --output text 2>/dev/null || echo "")
        
        if [ ! -z "$CLOUDFRONT_DOMAIN" ]; then
            echo "✅ CloudFront distribution found"
            CLOUDFRONT_URL="https://$CLOUDFRONT_DOMAIN"
        else
            echo "❌ Warning: Could not verify CloudFront distribution ID"
            CLOUDFRONT_DISTRIBUTION_ID=""
        fi
    fi
fi

# Create configuration file
echo ""
echo "💾 Creating configuration file..."

cat > scripts/aws-config.sh <<EOF
#!/bin/bash
# AWS Configuration for LER Landscaping Website
# This file was generated by connect-existing-aws.sh

export BUCKET_NAME="$BUCKET_NAME"
export AWS_REGION="$REGION"
export WEBSITE_URL="$WEBSITE_URL"
EOF

if [ ! -z "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
    cat >> scripts/aws-config.sh <<EOF

# CloudFront Configuration
export CLOUDFRONT_DISTRIBUTION_ID="$CLOUDFRONT_DISTRIBUTION_ID"
export CLOUDFRONT_URL="$CLOUDFRONT_URL"
EOF
fi

chmod +x scripts/aws-config.sh

echo "✅ Configuration saved to scripts/aws-config.sh"
echo ""

# Display summary
echo "=========================================="
echo "✅ Connection Setup Complete!"
echo "=========================================="
echo ""
echo "S3 Bucket: $BUCKET_NAME"
echo "Region: $REGION"
echo "Website URL: $WEBSITE_URL"

if [ ! -z "$CLOUDFRONT_URL" ]; then
    echo "CloudFront URL: $CLOUDFRONT_URL"
fi

echo ""
echo "Next steps:"
echo "1. Review your configuration: cat scripts/aws-config.sh"
echo "2. Deploy your website: ./scripts/deploy-s3.sh"
echo "3. Test deployment: ./scripts/test-deployment.sh"
echo ""
